services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    user: root
    volumes:
      - ./notebooks:/home/dev/workspace/notebooks
      - ~/.config/nvim:/root/.config/nvim
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    command: jupyter lab --ip=0.0.0.0 --port=9999 --allow-root
    working_dir: /home/dev/workspace
    network_mode: "host"

  jupyter-gpu:
    extends:
      service: jupyter
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
    profiles: ["gpu"]

